# pyproject.toml
[project]
name = "ruldani_scanner_lexer"
version = "0.1.0"

[tool.pytest.ini_options]
testpaths = ["./tests"]
pythonpath = ["./"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"