# pyproject.toml
[project]
name = "ruldani_scanner_lexer"
version = "0.1.0"

[project.optional-dependencies]
examples = []

[tool.pytest.ini_options]
testpaths = ["src/test"]
pythonpath = ["src"]

# Setup development environment
dev = "pip install -e .[dev,examples]"